on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: ".node-version"
          cache: npm
      - name: Install dependencies
        run: npm install
      - id: types
        name: Check types
        run: npm run tsc:check
        continue-on-error: true
      - id: lint
        if: ${{ success() || contains(fromJson('["success", "failure"]'), steps.types.outcome) }}
        name: Check lint rules
        run: npm run lint:check
        continue-on-error: true
      - id: format
        if: ${{ success() || contains(fromJson('["success", "failure"]'), steps.lint.outcome) }}
        name: Check format
        run: npm run format:check
        continue-on-error: true
      - id: test
        if: ${{ success() || contains(fromJson('["success", "failure"]'), steps.format.outcome) }}
        name: Test
        run: npm run test:ci
        continue-on-error: true
